/**
 * brief-mock-drafts — deterministic mocked model output for the fictional
 * Northwind Freight deal (Commit 2 / 2A tests). No live model calls.
 *
 * Content items are BUILT from the real EvidencePacket/ChangeSet so their ids,
 * fact bindings, provenance, confidence, and assurance are correct by
 * construction. Bindings are generated by enumerating each cited payload's
 * typed fields, so every concrete value in the text is bound.
 */

import { buildEvidencePacket, type EvidenceItem, type Provenance } from "@/lib/deck/brief-evidence";
import { detectChanges } from "@/lib/deck/brief-change-detection";
import { currentSnapshot, previousSnapshot } from "@/lib/deck/fixtures/brief-test-deal";
import {
  deriveAssurance,
  deriveConfidenceCeiling,
  deriveProvenanceUnion,
  selectTypedValue,
  type AssertionMode,
  type BriefContentItem,
  type BriefContentType,
  type BriefDraft,
  type BriefSection,
  type FactBinding,
} from "@/lib/deck/brief-model";
import { generateExecutiveBrief, type BriefRequest, type ValidatedExecutiveBrief } from "@/lib/deck/brief-agent";

export const packet = buildEvidencePacket(currentSnapshot);
export const previousPacket = buildEvidencePacket(previousSnapshot);
export const changeSet = detectChanges(packet, previousPacket);
export const noPriorChangeSet = detectChanges(packet, null);

export const request: BriefRequest = {
  packet,
  changeSet,
  cover: { dealName: "Northwind Freight — Dispatch Automation Rollout", companyName: "Northwind Freight", preparedFor: "RVP", asOf: "2026-07-18" },
};

/** The branded, validated+assembled Northwind brief — the ONLY input the
 *  renderer accepts. Produced through the real generateExecutiveBrief path. */
export async function renderableBrief(): Promise<ValidatedExecutiveBrief> {
  const res = await generateExecutiveBrief(request, async () => makeValidDraft());
  if (!res.ok) throw new Error(`renderableBrief: fixture failed validation — ${res.errors.map((e) => e.code).join(", ")}`);
  return res.brief;
}

// ── binding generation ────────────────────────────────────────────────────

const FIELDS: Record<string, string[]> = {
  opportunity_value: ["value", "field"],
  next_action: ["value", "origin"],
  transcript_statement: ["transcriptId", "segmentId", "side", "text"],
  intel_fact: ["value", "factKey"],
  stakeholder: ["value", "aspect", "stakeholderId", "name"],
  risk: ["severity", "title", "riskId"],
  commitment: ["state", "label", "expectedBy", "commitmentId", "party", "owner"],
  deal_posture: ["posture"],
  open_question: ["topic"],
};

function bindingsFor(item: EvidenceItem, changeId?: string): FactBinding[] {
  return FIELDS[item.payload.kind].flatMap((f) => {
    const value = selectTypedValue(item.payload, f);
    return value === undefined
      ? []
      : [{ evidenceId: item.evidenceId, sourceFactKey: item.sourceFactKey, payloadKind: item.payload.kind, fieldPath: f, value, ...(changeId ? { changeId } : {}) }];
  });
}

/** Under the executive-deck cap (≤2 factBindings/item), bind the values the text
 *  actually references (so entity checks pass), then take at most two. */
function pickBindings(all: FactBinding[], text: string): FactBinding[] {
  const relevant = all.filter((b) => text.includes(b.value));
  return (relevant.length ? relevant : all).slice(0, 2);
}

export const one = (lk: string): EvidenceItem => packet.items.find((i) => i.logicalKey === lk)!;
const all = (lk: string): EvidenceItem[] => packet.items.filter((i) => i.logicalKey === lk);
export const factKeyOf = (lk: string): string => one(lk).sourceFactKey;
export const seg = (transcriptId: string, segmentId: string): EvidenceItem =>
  packet.items.find((i) => i.payload.kind === "transcript_statement" && i.payload.transcriptId === transcriptId && i.payload.segmentId === segmentId)!;

export function fromItems(
  id: string,
  contentType: BriefContentType,
  section: BriefSection,
  items: EvidenceItem[],
  text: string,
  assertionMode: AssertionMode,
  extra: Partial<BriefContentItem> = {},
): BriefContentItem {
  return {
    id,
    contentType,
    section,
    text,
    assertionMode,
    evidenceIds: [...new Set(items.map((i) => i.evidenceId))].slice(0, 3),
    sourceFactKeys: [...new Set(items.map((i) => i.sourceFactKey))].slice(0, 3),
    factBindings: pickBindings(items.flatMap((i) => bindingsFor(i)), text),
    provenance: deriveProvenanceUnion(items).slice(0, 3),
    confidence: deriveConfidenceCeiling(items),
    assurance: deriveAssurance(items),
    appendixEligible: true,
    ...extra,
  };
}

function packetItem(
  id: string,
  contentType: BriefContentType,
  section: BriefSection,
  keys: string[],
  text: string,
  assertionMode: AssertionMode,
  extra: Partial<BriefContentItem> = {},
): BriefContentItem {
  return fromItems(id, contentType, section, keys.map(one), text, assertionMode, extra);
}

function changeItem(id: string, type: string, text: string, assertionMode: AssertionMode): BriefContentItem {
  const c = changeSet.changes.find((x) => x.type === type)!;
  const resolvable = c.currentEvidenceIds
    .map((eid) => packet.items.find((i) => i.evidenceId === eid))
    .filter((x): x is EvidenceItem => !!x);
  const bindings = resolvable.flatMap((i) => bindingsFor(i, c.changeId));
  if (bindings.length === 0) {
    // Removed: reference the change via a prior-side binding (typed value check
    // is skipped because the prior payload is not in the current packet).
    bindings.push({ evidenceId: c.previousEvidenceIds[0], sourceFactKey: c.sourceFactKeys[0], payloadKind: "commitment", fieldPath: "state", value: "open", changeId: c.changeId });
  }
  const provenance: Provenance[] = resolvable.length ? deriveProvenanceUnion(resolvable) : c.assurance === "unresolved" ? ["open_question"] : ["mallin_inference"];
  return {
    id,
    contentType: "what_changed",
    section: "what_changed",
    text,
    assertionMode,
    evidenceIds: [...new Set([...c.previousEvidenceIds, ...c.currentEvidenceIds])].slice(0, 3),
    sourceFactKeys: c.sourceFactKeys.slice(0, 3),
    factBindings: pickBindings(bindings, text),
    provenance: provenance.slice(0, 3),
    confidence: deriveConfidenceCeiling(resolvable),
    assurance: c.assurance,
    appendixEligible: true,
  };
}

/** A fresh, fully-valid Northwind brief draft. */
export function makeValidDraft(): BriefDraft {
  return {
    executiveSummary: [
      packetItem("es1", "executive_conclusion", "executive_summary", ["deal:posture"], "Deal posture is at_risk heading into the next call.", "sourced_fact"),
      packetItem("es2", "executive_conclusion", "executive_summary", ["risk:r_champion_exit"], "The champion is transitioning out, putting continuity at risk.", "sourced_fact"),
      packetItem("es3", "executive_conclusion", "executive_summary", ["opp:amount"], "Deal amount remains unconfirmed.", "unresolved"),
    ],
    whatChanged: [
      changeItem("wc1", "stage_change", "Stage advanced from Discovery to Evaluation.", "sourced_fact"),
      changeItem("wc2", "close_date_change", "Close date moved to 2026-11-15.", "sourced_fact"),
      changeItem("wc3", "posture_change", "Deal posture shifted from advancing to at_risk.", "supported_synthesis"),
    ],
    customerPriorities: [
      packetItem("cp1", "customer_priority", "priorities", ["intel:priority:peak-season-reliability"], "Reducing peak-season dispatch errors is the stated top operational priority.", "sourced_fact"),
      packetItem("cp2", "customer_priority", "priorities", ["txn:call_nw_2:0"], "The buyer signaled willingness to proceed if cutover is phased after peak.", "sourced_fact"),
    ],
    stakeholders: [
      packetItem("sh1", "stakeholder_assessment", "stakeholders", ["stk:sh_dana:disposition"], "Dana Ruiz has shifted to a supporter.", "sourced_fact"),
      packetItem("sh2", "stakeholder_assessment", "stakeholders", ["stk:sh_marcus:role"], "Marcus Bell is read as the deal champion.", "sourced_fact"),
    ],
    decisionProcess: [
      packetItem("dp1", "decision_process", "decision_process", ["opp:stage"], "The deal is in the Evaluation stage.", "sourced_fact"),
      packetItem("dp2", "decision_process", "decision_process", ["opp:closeDate"], "Target close date is 2026-11-15.", "sourced_fact"),
      fromItems("dp3", "decision_process", "decision_process", all("deal:nextAction"), "The recorded CRM next step and the recommended next action disagree.", "unresolved"),
    ],
    risks: [
      packetItem("rk1", "risk", "risks", ["risk:r_champion_exit"], "Champion transition threatens continuity; no successor sponsor identified.", "sourced_fact"),
      packetItem("rk2", "risk", "risks", ["risk:r_integration"], "Telematics integration feasibility is still unproven.", "sourced_fact"),
      packetItem("rk3", "risk", "risks", ["opp:amount"], "Deal amount is unconfirmed, limiting forecast confidence.", "unresolved"),
    ],
    actionPlan: {
      customerCommitments: [
        // CONFIRMED via an explicit buyer-stated segment (chain cited).
        fromItems("ac1", "customer_commitment", "action_plan", [one("commit:c_voldata"), seg("call_nw_1", "1")], "Dana Ruiz committed to provide peak-season volume data.", "sourced_fact"),
        // CONFIRMED via a seller-recorded customer commitment (retains seller provenance).
        fromItems("ac2", "customer_commitment", "action_plan", [one("commit:c_sponsor"), seg("call_nw_1", "2")], "Dana Ruiz agreed to sponsor the internal review, per the rep's note.", "sourced_fact"),
      ],
      inferredCustomerCommitments: [
        // INFERRED possible commitment — labeled, never presented as agreed.
        packetItem("ic1", "inferred_customer_commitment", "action_plan", ["commit:c_pilot"], "A paid pilot is a possible customer commitment — inferred, not yet agreed.", "supported_synthesis"),
      ],
      sellerActions: [
        packetItem("as1", "seller_action", "action_plan", ["commit:c_security"], "Security review packet completed and signed off.", "sourced_fact", {
          commitmentClaim: { sourceFactKey: factKeyOf("commit:c_security"), status: "completed" },
        }),
      ],
      mallinRecommendations: [
        packetItem("ar1", "mallin_recommendation", "action_plan", ["risk:r_champion_exit"], "Recommend securing a successor sponsor before the champion departs.", "mallin_recommendation"),
      ],
      unresolvedActions: [
        fromItems("au1", "unresolved_action", "action_plan", all("deal:nextAction"), "The next action is contested between the CRM step and the recommended action; resolve before the call.", "unresolved", {
          nextActionClaim: true,
        }),
      ],
    },
    appendix: [],
  };
}

/** A valid draft that exceeds the risks budget → overflow must go to appendix. */
export function makeOverBudgetDraft(): BriefDraft {
  const d = makeValidDraft();
  const extras = ["ov1", "ov2", "ov3", "ov4"].map((id) =>
    packetItem(id, "risk", "risks", ["risk:r_integration"], "Telematics integration feasibility is still unproven.", "sourced_fact"),
  );
  d.risks = [...d.risks, ...extras];
  return d;
}
